DROP TABLE Part PURGE;
DROP TABLE Car PURGE;
DROP TABLE Pallet PURGE;
DROP TABLE Product PURGE;

-- 
    
CREATE TABLE Car
    (
        id 				NUMBER(6, 0) 
			GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        chassisNumber 	VARCHAR(17) NOT NULL
            CONSTRAINT coCarChasNumber UNIQUE,
        manufacturer 	VARCHAR(50) NOT NULL,
        model 			VARCHAR(50) NOT NULL,
        year 			NUMBER(4, 0) NOT NULL,
        weight 			DOUBLE PRECISION NOT NULL,   
		state 			VARCHAR(30) NOT NULL
                        CONSTRAINT carStateCheck CHECK 
                          (state IN ('In progress', 'Finished'))
    );    
    
-- 
    
CREATE TABLE Product
    (
        id 				NUMBER(6, 0) 
			GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        type 			VARCHAR(50) NOT NULL,
        name 			VARCHAR(100) NOT NULL
    );    
    
--
    
CREATE TABLE Pallet
    (
        id 				NUMBER(6, 0) 
			GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        partType 		VARCHAR(100) NOT NULL,
        weight 		    DOUBLE PRECISION NOT NULL,
        maxWeight 		DOUBLE PRECISION NOT NULL,
		state 			VARCHAR(30) NOT NULL
                        CONSTRAINT palletStateCheck CHECK 
                          (state IN ('In progress', 'Finished'))
    );    
    
--
    
CREATE TABLE Part
    (
        id 				NUMBER(6, 0) 
			GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        type 			VARCHAR(50) NOT NULL,
        weight 			DOUBLE PRECISION NOT NULL,
        carId 			NUMBER(6, 0) NOT NULL
			REFERENCES Car (id),
        palletId 		NUMBER(6, 0) NOT NULL
            REFERENCES Pallet (id),
        productId 		NUMBER(6, 0) NOT NULL
            REFERENCES Product (id)
    );    

-- ##################################
-- INSERTS AFTER TABLES WERE CREATED
-- ##################################

INSERT INTO Pallet (id, partType, weight, maxWeight, state)
    VALUES (-1, 'no pallet', 0, 0, 'Finished');
    
INSERT INTO Product (id, type, name)
    VALUES (-1, 'no product', 'no product');
COMMIT;